version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - pdf_enc:/data/db

volumes:
  pdf_enc: